/*
    ESTE ARCHIVO DE CABECERA CONTIENE TODAS LAS CONSTANTES QUE SE UTILIZARON 
    PARA EL DESARROLLO DEL PARCIAL.
*/

#define VERSIONS_DB "versions.db"
#define VERSIONS_DIR ".versions"
#define VERSIONS_PATH VERSIONS_DIR "/" VERSIONS_DB
#define VERSIONS_FILE ".versions/versions.db"